config/routes.rb
Olccs::Application.routes.draw do

  root :to => 'welcome#index'

  match '/post.php' => 'welcome#postphp', :via => :post
  match '/backend.php' => 'welcome#backendphp', :via => :get
  match '/totoz.php' => 'welcome#totozphp', :via => :get
  match '/urls(.:format)' => 'welcome#urls', :via => :get
  
  match '/t(/:tribune(/:action))(.:format)' => 'tribune', :as => 'tribune'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/session/destroy', :to => 'sessions#destroy', :as => 'signout'

  match '/u' => 'user#index', :as => :user
  match '/u/save_olcc_cookie' => 'user#save_olcc_cookie', :as => :save_olcc_cookie
  match '/u/reload_olcc_cookie' => 'user#reload_olcc_cookie', :as => :reload_olcc_cookie
  match '/u(/:action(.:format))' => 'user'

  match '/about' => 'welcome#about'
  match '/help' => 'welcome#help'
  match '/api' => 'welcome#api'
  match '/boards.xml' => 'welcome#boards'

  #match ':controller(/:action(/:id))(.:format)'
end

app/models/tribune.rb
# encoding: UTF-8

# Modèle de représentation de tribune. Effectue toutes les interractions avec la tribune cible et présente aux
# modèles et controlleurs utilisateurs une API standard quelque soit la tribune.
class Tribune < ActiveRecord::Base
  has_many :posts
  has_many :links, :through => :posts
  has_many :rules

  attr_accessible :cookie_name, :cookie_url, :get_url, :last_id_parameter, :name, :post_parameter, :post_url,
                  :pwd_parameter, :user_parameter, :last_updated, :remember_me_parameter, :refresh_interval, :type_slip

  validates_uniqueness_of :name

  TYPE_SLIP_RAW = 0
  TYPE_SLIP_ENCODED = 1

  # TODO Faire un chargement par fichier remote.xml afin de charger un historique

  # Génère le backend pour la tribune. Si un utilisateur est connecté, on effectué également une percolation de chacun
  # des posts du backend pour lancer les actions dessus.
  # @param [Hash] opts
  def backend(opts={})
    # s supprimé de la liste: utilisation de la pagination avec du per_page de kaminari
    conf = {
        :last => -1073741824,
        :user => nil,
        :page => 1,
    }.merge(opts)
    # TODO ça merde avec la pagination, le p_id > 0 certainement
    b = self.posts.page(conf[:page]).where("p_id > ?", conf[:last]).order("p_id DESC")

    #b = Tire.search(name) do
    #  query do
    #    range :id, {:from => last.to_i+1}
    #  end
    #  sort do
    #    by :id, 'desc'
    #  end
    #  size s
    #end

    #r = b.results.results.collect do |i|
    #  i['_source']
    #end

    return [b.to_a, b] if conf[:user].nil? or conf[:user].rules.size == 0

    logger.debug("On commence la percolation")
    md5 = conf[:user].md5

    index = Tire.index(name)

    res = b.collect do |content|
      #raise content['message'].to_yaml
      matches = index.percolate(message: content.message, time: content.time, login: content.login, info: content.info, type: 'post') do
        term :md5, md5
      end

      #raise matches.to_yaml
      unless matches.nil?
        matched = []
        matches.each do |m|
          rule_name = m.split('_')[1]
          rule = conf[:user].rules.find_by_name(rule_name)

          action = rule.action.to_sym
          #raise rule.to_yaml
          logger.debug "ici, dans le filtre, #{content.inspect} pour #{rule_name}"
          plop = OlccsPluginsManager.instance.repository[action]
          unless plop.nil?
            new_message = plop.instance.process(content['message'])
            content['message'] = new_message
            matched << action
          end
        end
        content['rules'] = matched.join(',')
      end
      content
    end
    #raise res.to_yaml
    [res, b]
  end

  # Effectue une recherche dans Elasticsearch pour la tribune
  # TODO: refaire cette partie pour options en hash
  def query(q, page=1, s=150)
    b = Tire.search(name) do
      query do
        string q, default_operator: "AND", default_field: "message"
      end
      highlight :message, :options => { :tag => '<span class="label">' }
      sort do
        by :id, 'desc'
      end
      from (page.to_i - 1) * s
      size s.to_i
    end
    #logger.debug(b.to_json)

  end

  # Effectue le rafraichissement de la tribune
  #
  # * Lance la requête vers la tribune cible avec le last id positionné
  # * Filtre le contenu avec Nokogiri pour (au cas où la tribune n'accepte pas le last id)
  def refresh
    client = HTTPClient.new
    last_post = self.posts.last(:order => "p_id")
    if last_post.nil?
      last_id = 0
    else
      last_id = last_post.p_id
    end
    query = {"#{last_id_parameter}" => last_id}

    begin
      r = client.get(get_url, query)

      #puts "*"*80
      #puts "#{name} => " + r.content #.force_encoding('utf-8').encoding.to_s
      #puts "#{name} => " + r.body_encoding.to_s
      #puts "*"*80
      response = Nokogiri::XML(r.content)
      response.xpath("/board/post[@id > #{last_id}]").reverse.each do |p|
        puts ">>= #{p.xpath('message')} =<<"
        p_id = p.xpath("@id").to_s.to_i
        self.posts.build({p_id: p.xpath("@id").to_s.to_i,
                          time: p.xpath("@time").to_s,
                          info: p.xpath("info").text.encode('utf-8').strip,
                          login: p.xpath("login").text.encode('utf-8').strip,
                          message: p.xpath("message")
                         })

      end
      save!
      Tire.index name do
        self.refresh
      end
    rescue HTTPClient::BadResponseError => e
      logger.error ("Refresh failed for #{name}")
      logger.error (e)
    ensure
      update_column :last_updated, Time.now
    end
  end

  def refresh?
    RefreshWorker.perform_async(id)
  end

  # Lance le refresh conditionnel sur toutes les tribunes
  def self.refresh_all
    Tribune.all.each do |t|
      t.refresh?
    end
  end

  # Permet le login sur la tribune cible par envoie du login/mdp vers le formulaire de login, et retourne les cookies
  #
  # TODO: mettre à jour la partie sur les cookies pour renvoyer ce que plopoid accepte
  # @param [Hash<user,password>] opts Paramètre contenant nom d'utilisateur et mot de passe
  # @return [Hash] Renvoie le hash de cookies
  def login(opts)
    client = HTTPClient.new
    client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE

    body = {
        user_parameter.to_sym => opts[:user],
        pwd_parameter.to_sym => opts[:password]
    }
    body[remember_me_parameter.to_sym] = 1 unless remember_me_parameter.nil?
    head = {
        :Referer => cookie_url,
        :User_Agent => opts[:ua]
    }

    r = client.post(cookie_url, body, head)
    client.cookie_manager.cookies
  end

  # Poste un nouveau message sur la tribune cible
  #
  # TODO: refaire la partie sur les cookies
  # @param [Hash<message, ua, cookies>] opts Hash de paramètre
  # @return [Integer] Renvoie le X-Post-Id du post (nil si la tribune ne renvoie pas de X-Post-Id)
  def post(opts)

    client = HTTPClient.new
    body = {
        post_parameter.to_sym => opts[:message]
    }
    head = {
        :Referer => post_url,
        "User-Agent" => opts[:ua]
    }

    unless opts[:cookies].nil? and opts[:cookies]==''
      if opts[:cookies].class == String
        client.cookie_manager.parse(opts[:cookies], URI.parse(post_url))
      elsif opts[:cookies].class == Hash
        opts[:cookies].each do |k, v|
          if v != ""
            c = "#{k}=#{v.encode('utf-8')}"
            client.cookie_manager.parse(c, URI.parse(post_url))
          end
        end
      end
    end

    res = client.post(post_url, body, head)

    self.refresh

    return res.headers['X-Post-Id']

  rescue Exception => e
    logger.error("Post fail for #{name}")
    logger.error(opts)
    logger.error(e)
    logger.error(e.backtrace)
  end

  # Chargement en masse de posts dans la base
  #
  # Charge chaque csv dans une transaction pour optimiser les temps de traitement
  #
  # Liste des champs dans le CSV: post_id, time (format YYYYMMDDhhmmss), login, info/ua, message
  #
  # Dans phpmyadmin, faire un export format csv pour excel.
  # @param [String] directory Chemin où sont situés les fichiers .csv

  #def load_from_csv(directory)
  #  cpt = 0
  #  coder = HTMLEntities.new # pour vieux posts dlfp
  #  # sed -i.bak 's/"N,//' *.csv
  #
  #  Dir.glob(directory+'/*.csv') do |filename|
  #    puts "Gestion de #{filename} à #{Time.now}"
  #    #transaction do
  #      CSV.foreach(filename, {:col_sep => ','}) do |r|
  #        cpt+=1
  #        puts r[0].to_i
  #        # pour ancien site dlfp
  #        p_id = r[0].to_i - 3050553
  #        id = p_id
  #        time = Time.strptime(r[1], '%Y-%m-%d %H:%M:%S').strftime('%Y%m%d%H%M%S')
  #        login = r[2] || ""
  #        info = r[3] || ""
  #        # pour dlfp. Sinon, supprimer le decode
  #        message = coder.decode(r[4]) || ""
  #
  #        self.posts.build({p_id: p_id,
  #                          time: time,
  #                          info: info.encode('utf-8').strip,
  #                          login: login.encode('utf-8').strip,
  #                          message: "<message>#{message.encode('utf-8').strip}</message>"
  #                         })
  #      end
  #    #end
  #    save!
  #    puts "#{filename} terminé à #{Time.now}"
  #    File.rename(filename, "#{filename}.done")
  #  end
  #
  #rescue Exception => e
  #  puts e
  #  puts e.backtrace
  #end
end

app/controllers/tribune_controller.rb
# encoding: UTF-8

# Controleur de gestion de tribune, gère le multiformat xml/rss/html/json là où c'est nécessaire. Se réferer à la document
# de l'API pour les informations nécessaires
class TribuneController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  protect_from_forgery :except => [:post, :login]

  before_filter :set_tribune

  #def populate_perco
  #  redirect_to root_url if current_user.nil?
  #  user = current_user
  #  md5 = Digest::MD5.hexdigest("#{user.provider}#{user.uid}")
  #  Tire.index(@tribune.name) do
  #    register_percolator_query("#{md5}_ototu", :md5 => md5) { string 'login:ototu' }
  #  end
  #end

  # Voir la doc d'API
  def index
    #raise Rails.application.config.assets.paths.to_yaml
    last = params[:last] || -1073741824
    page = params[:page] || 1
    # size = params[:size] || 150 cf partie dans tribune.rb => param supprimé
    r = @tribune.backend(:last => last, :user => current_user, :page => page)
    @results = r[0]
    @posts = r[1]

    #raise @results.to_yaml

    respond_to do |format|
      format.html
      format.json
    end

  end

  def xmlconfig
#    <?xml version="1.0" encoding="utf-8" ?>
#        <site name="kadreg" title="Da lent bouchot" baseurl="http://kadreg.org" version="1.0" xmlns="urn:moules:board:config:1.0">
#    <account>
#    <cookie name="md5"/>
#    <cookie name="unique_id"/>
#    <login method="post" path="/login.html">
#    <field name="login">$l</field>
#<field name="passwd">$p</field>
#    </login>
#<logout method="get" path="/close_session.html"/>
#</account>
#<module type="application/board+xml" name="board" title="Tribune">
#<backend path="/board/backend.php" public="true" tags_encoded="false" refresh="60"/>
#<post method="post" path="/board/add.php" anonymous="false" max_length="128">
#<field name="message">$m</field>
#</post>
#</module>
#</site>
  end

  # Voir la doc d'API
  def remote
    last = params[:last] || 0
    page = params[:page] || 1

    @results = @tribune.backend({:last => last, :user => current_user, :page => page})[0]
    #raise @results.to_yaml
    #res = nil
    #
    #if current_user
    #  puts "percolation pour #{@current_user.name}"

    #end

    respond_to do |format|
      format.tsv
      format.xml { render xml: posts_to_xml(@results, @tribune.name) }
    end

  end

  # Voir la doc d'API
  def post
    last = params[:last] || -1073741824

    x = @tribune.post message: params[:message],
        ua: request.user_agent,
        cookies: request.cookies

    unless x.nil?
      response.headers['X-Post-Id'] = x
    end

    @results = @tribune.backend({:last => last, :user => current_user})[0]

    respond_to do |format|
      format.html { render :nothing => true}
      format.tsv { render :template => 'tribune/remote'}
      format.xml {render xml: posts_to_xml(@results, @tribune.name) }
    end

    #render :nothing => true
  end

  # Voir la doc d'API
  def search
    # TODO: pour la recherche, prévoir à l'affichage un truc pour prendre les posts des horloges pointées, et éventuellement un "contexte" en nombre de lignes affichables
    size = params[:size] || 150
    page = params[:page] || 1
    @results = []
    if params[:query].blank?
      respond_to do |format|
        format.html { render }
        format.xml { render :nothing => true}
        format.tsv { render :nothing => true}
      end
    else
      @results = @tribune.query(params[:query],page,150).results
      #raise @results.to_yaml
      respond_to do |format|
        format.html
        format.xml { render :xml => search_to_xml(@results, @tribune.name) }
        format.tsv
      end
    end

  end

  # Voir la doc d'API
  def stats
  end

  # Voir la doc d'API
  def urls
    @urls = @tribune.links.order("created_at desc").limit(42)

    respond_to do |format|
      format.html
      format.rss
      format.xml {render :xml => urls_to_xml(@urls, @tribune.name)}
    end

  end

  # Voir la doc d'API
  def login
    tribune_login = @tribune.login({user: params[:user], password: params[:password], ua: "plop"})

    tribune_login.each {|c|
      cookies[c.name] = { value: c.value, expires: c.expires }
    }
    render :json => tribune_login.to_json
  end

  # Voir la doc d'API
  def history
  end

  # Voir la doc d'API
  def refresh
    @tribune.refresh
  end

private
  def set_tribune
    @tribune = Tribune.find_by_name(params[:tribune]) || raise(ActiveRecord::RecordNotFound)
  end

  def record_not_found
    render :text => "404 Not Found", :status => 404
  end

end

app/helpers/tribune_helper.rb
module TribuneHelper
end

app/views/tribune/_post.html.erb
<%
   time = Time.strptime(post['time'], '%Y%m%d%H%M%S').strftime('%H:%M:%S')
   d = post['info'][0..20]
   t = post['info']
   class_d = 'ua'
   if post['login'] != ''
     d = post['login']
     t = post['info']
     class_d = 'login'
   end
   re = Regexp.new("(?<=\s|^|>|#)(?:(?:([0-2]?[0-9])\:([0-5][0-9])\:([0-5][0-9])|([0-2]?[0-9])([0-5][0-9])([0-5][0-9]))(?:[\:\^]([0-9]{1,2})|([¹²³]))?)|([0-2]?[0-9])\:([0-5][0-9])(?=\s|$|<)")
   message = post['message'].gsub(re) {|s|
     "<span class='horloge_ref'>#{s}</span>"
   }


   display = post['login'].presence || post['info'] %>
<li class='post' id="p<%=post['id']-%>"><span class="horloge"><%=time%></span> <span title="<%=post['info']%>" class="<%=class_d%>"><%=d%></span> <span class="message"><%=raw message %></span></li>

app/views/tribune/_result.json.erb
<%
time = Time.strptime(result['time'], '%Y%m%d%H%M%S').strftime('%H:%M:%S')
ua_or_login = result['info'][0..20]
class_display = 'ua'
if result['login'] != ''
   ua_or_login = result['login']
   class_display = 'login'
end
re = Regexp.new("(?<=\s|^|>|#)(?:(?:([0-2]?[0-9])\:([0-5][0-9])\:([0-5][0-9])|([0-2]?[0-9])([0-5][0-9])([0-5][0-9]))(?:[\:\^]([0-9]{1,2})|([¹²³]))?)|([0-2]?[0-9])\:([0-5][0-9])(?=\s|$|<)")
totoz = Regexp.new("\\\[:([0-9a-zA-Z \*\$@'_-]+)\\\]")
message = result['message'].gsub(re) {|s|
   "<span class='horloge_ref'>#{s}</span>"
}
message.gsub!(totoz) {|s|
    "<span class='totoz'>#{s}</span>"
}

display = result['login'].presence || result['info']
%>
{
    "id": <%=result['p_id']%>,
    "time":"<%=time%>",
    "info":<%=raw result['info'].to_json%>,
    "class_display":"<%=class_display%>",
    "ua_or_login":<%=raw ua_or_login.to_json%>,
    "message":<%=raw message.to_json%>,
    "rules": "<%=result['rules']%>"
}

app/views/tribune/_search_result.html.erb
<%
   c = post['_source']
   time = Time.strptime(c['time'], '%Y%m%d%H%M%S').strftime('%H:%M:%S')
   d = c['info'][0..20]
   t = c['info']
   class_d = 'ua'
   if c['login'] != ''
     d = c['login']
     t = c['info']
     class_d = 'login'
   end

   if post['highlight']
     message = post['highlight']['message'][0]
   else
     message = c['message']
   end

   #re = Regexp.new("(?<=\s|^|>|#)(?:(?:([0-2]?[0-9])\:([0-5][0-9])\:([0-5][0-9])|([0-2]?[0-9])([0-5][0-9])([0-5][0-9]))(?:[\:\^]([0-9]{1,2})|([¹²³]))?)|([0-2]?[0-9])\:([0-5][0-9])(?=\s|$|<)")
   #message = message.gsub(re) {|s|
   #  "<span class='horloge_ref'>#{s}</span>"
   #}

   display = c['login'].presence || c['info'] %>
<li class='c' id="p<%= c['id'] -%>">
  <a href="<%= tribune_path(tribune: @tribune.name, anchor: "p#{c['id']}", page: Post.where("tribune_id = ? and p_id = ?", @tribune.id, c['id'])[0].num_page) %>"><i class=" icon-share"></i></a>
  <span class="horloge"><%= time %></span>
  <span title="<%= c['info'] %>" class="<%= class_d %>"><%= d %></span>
  <span class="message"><%= raw message %></span>
</li>

app/views/tribune/_spacer.erb
,

app/views/tribune/_url.html.erb
<li class="span4">
  <div class="thumbnail">
    <% md5 = Digest::MD5.hexdigest(URI.escape(url.href)) %>
    <%= image_tag "#{md5}/site-thumbnail.png" %>

    <div class="caption">
      <p><%= link_to truncate(url.href, length: 45), url.href %></p>

      <p>
    </div>
  </div>
</li>

app/views/tribune/history.html.erb
<h1>Tribune#history</h1>
<p>Find me in app/views/tribune/history.html.erb</p>

app/views/tribune/index.html.erb
<% content_for :navbar do %>
    <li><%= link_to "Search", :controller => 'tribune', :action => 'search' %></li>
    <li><%= link_to "Stats", :controller => 'tribune', :action => 'stats' %></li>
<% end %>

<h2><%= @tribune.name %></h2>
<p><%= @tribune.posts.count %> posts, <%= @tribune.links.count %> links.</p>

<div id="tribune">
  <ul id="list_tribune">
  </ul>
  <%= paginate @posts , theme: 'bootstrap' %>
  <%= form_tag url_for(:action => 'post'), :id => 'form_post', :remote => true do |f| %>
      <%= text_field_tag 'message', nil, :class => 'span8', :placeholder => 'Message' %><%= button_tag 'Poster', :class => 'btn', :id => "submit" %>
  <% end %>
  <!--<div id="postDiv"><input id="missive" maxlength="600" name="missive" size="80" type="text" value=""  disabled="disabled" />-->
  <!--<input name="commit" type="submit" value="Poster" disabled="disabled"/>-->
  <!--<img alt="Spinner" id="please_wait" src="/images/spinner.gif?1184154283" style="visibility:hidden" />-->
  <!--<img alt="Autoreload" id="autoreload" src="/images/autoreload.gif?1184154283" style="visibility:hidden" />-->

</div>

app/views/tribune/index.json.erb
{
    "board":{
        "site": "<%=@tribune.name%>"
    },
    "posts":[
            <%= render :partial => 'result', :collection => @results, :spacer_template => 'spacer' %>
    ]
}

app/views/tribune/login.html.erb
<h1>Tribune#login</h1>
<p>Find me in app/views/tribune/login.html.erb</p>

app/views/tribune/post.html.erb
<h1>Tribune#post</h1>
<p>Find me in app/views/tribune/post.html.erb</p>

app/views/tribune/remote.html.erb
<h1>Tribune#remote</h1>
<p>Find me in app/views/tribune/remote.html.erb</p>

app/views/tribune/search.html.erb
<% if @results.size !=0 %>
<ol>
  <% @results.each do |res|
    if res['_type'] == 'link' %>
        <li class="link"><%= res['_source']['href'] %></li>
    <% else %>
      <%=  render 'search_result', post: res %>
    <%end%>
  <%end%>
</ol>
<% end %>

<%= paginate @results, theme: 'bootstrap' unless @results.empty? %>

<%= form_tag url_for action: 'search', method: 'get' do |f| %>
    <div class="field">
      <%= label_tag "Query: " %>
      <%= text_field_tag 'query' %>
    </div>
<% end %>

app/views/tribune/stats.html.erb
<h1>Tribune#stats</h1>
<p>Find me in app/views/tribune/stats.html.erb</p>

app/views/tribune/urls.html.erb
<ul class="thumbnails">
  <% @urls.each do |u| %>
    <%= render 'url', url: u %>
  <% end %>
</ul>